# Generated by Django 5.0.3 on 2024-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_owner_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
